/* eslint-disable */
/* prettier-ignore */

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: never;
  subscription: never;
  types: {
    'Aired': { kind: 'OBJECT'; name: 'Aired'; fields: { 'from': { name: 'from'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'to': { name: 'to'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'Anime': { kind: 'OBJECT'; name: 'Anime'; fields: { 'aired': { name: 'aired'; type: { kind: 'OBJECT'; name: 'Aired'; ofType: null; } }; 'airing': { name: 'airing'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; 'background': { name: 'background'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'characters': { name: 'characters'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Character'; ofType: null; }; }; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'duration': { name: 'duration'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'episodes': { name: 'episodes'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'genres': { name: 'genres'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Genre'; ofType: null; }; }; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'image': { name: 'image'; type: { kind: 'OBJECT'; name: 'AnimeImage'; ofType: null; } }; 'popularity': { name: 'popularity'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'producers': { name: 'producers'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Metadata'; ofType: null; }; }; } }; 'rank': { name: 'rank'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'rating': { name: 'rating'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'score': { name: 'score'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'season': { name: 'season'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'source': { name: 'source'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'status': { name: 'status'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'studios': { name: 'studios'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Metadata'; ofType: null; }; }; } }; 'synopsis': { name: 'synopsis'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'titles': { name: 'titles'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AnimeTitle'; ofType: null; }; }; } }; 'trailer': { name: 'trailer'; type: { kind: 'OBJECT'; name: 'Trailer'; ofType: null; } }; 'type': { name: 'type'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'year': { name: 'year'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'AnimeImage': { kind: 'OBJECT'; name: 'AnimeImage'; fields: { 'default': { name: 'default'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'large': { name: 'large'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'small': { name: 'small'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'AnimeOrderEnum': { name: 'AnimeOrderEnum'; enumValues: 'end_date' | 'episodes' | 'favorites' | 'mal_id' | 'popularity' | 'rank' | 'score' | 'scored_by' | 'start_date' | 'title'; };
    'AnimeTitle': { kind: 'OBJECT'; name: 'AnimeTitle'; fields: { 'title': { name: 'title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'type': { name: 'type'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'AnimeTypeEnum': { name: 'AnimeTypeEnum'; enumValues: 'cm' | 'movie' | 'music' | 'ona' | 'ova' | 'pv' | 'special' | 'tv' | 'tv_special'; };
    'Boolean': unknown;
    'Character': { kind: 'OBJECT'; name: 'Character'; fields: { 'about': { name: 'about'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'anime': { name: 'anime'; type: { kind: 'OBJECT'; name: 'Anime'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'image': { name: 'image'; type: { kind: 'OBJECT'; name: 'CharacterImage'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'nicknames': { name: 'nicknames'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; } }; 'url': { name: 'url'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'CharacterImage': { kind: 'OBJECT'; name: 'CharacterImage'; fields: { 'default': { name: 'default'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'small': { name: 'small'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'CharacterQueryParams': { kind: 'INPUT_OBJECT'; name: 'CharacterQueryParams'; isOneOf: false; inputFields: [{ name: 'limit'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'page'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }]; };
    'FilterEnum': { name: 'FilterEnum'; enumValues: 'airing' | 'bypopularity' | 'favorite'; };
    'Float': unknown;
    'Genre': { kind: 'OBJECT'; name: 'Genre'; fields: { 'animes': { name: 'animes'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Anime'; ofType: null; }; }; } }; 'count': { name: 'count'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'url': { name: 'url'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'GenresFilterEnum': { name: 'GenresFilterEnum'; enumValues: 'demographics' | 'explicit_genres' | 'genres' | 'themes'; };
    'GenresQueryParams': { kind: 'INPUT_OBJECT'; name: 'GenresQueryParams'; isOneOf: false; inputFields: [{ name: 'filter'; type: { kind: 'ENUM'; name: 'GenresFilterEnum'; ofType: null; }; defaultValue: null }]; };
    'ID': unknown;
    'Int': unknown;
    'Metadata': { kind: 'OBJECT'; name: 'Metadata'; fields: { 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'type': { name: 'type'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'url': { name: 'url'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'getAnime': { name: 'getAnime'; type: { kind: 'OBJECT'; name: 'Anime'; ofType: null; } }; 'getAnimesByGenres': { name: 'getAnimesByGenres'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Anime'; ofType: null; }; }; }; } }; 'getAnimesSearch': { name: 'getAnimesSearch'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Anime'; ofType: null; }; }; }; } }; 'getGenres': { name: 'getGenres'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Genre'; ofType: null; }; }; } }; 'getTopAnimes': { name: 'getTopAnimes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Anime'; ofType: null; }; }; }; } }; 'getTopCharacters': { name: 'getTopCharacters'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Character'; ofType: null; }; }; }; } }; 'me': { name: 'me'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; }; };
    'RatingEnum': { name: 'RatingEnum'; enumValues: 'g' | 'pg' | 'pg13' | 'r' | 'r17' | 'rx'; };
    'SearchAnimeQueryParams': { kind: 'INPUT_OBJECT'; name: 'SearchAnimeQueryParams'; isOneOf: false; inputFields: [{ name: 'end_date'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'filter'; type: { kind: 'ENUM'; name: 'FilterEnum'; ofType: null; }; defaultValue: null }, { name: 'genres'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'limit'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'order_by'; type: { kind: 'ENUM'; name: 'AnimeOrderEnum'; ofType: null; }; defaultValue: null }, { name: 'page'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'q'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'rating'; type: { kind: 'ENUM'; name: 'RatingEnum'; ofType: null; }; defaultValue: null }, { name: 'sfw'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: 'sort'; type: { kind: 'ENUM'; name: 'SearchSortEnum'; ofType: null; }; defaultValue: null }, { name: 'start_date'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'type'; type: { kind: 'ENUM'; name: 'AnimeTypeEnum'; ofType: null; }; defaultValue: null }]; };
    'SearchSortEnum': { name: 'SearchSortEnum'; enumValues: 'asc' | 'desc'; };
    'String': unknown;
    'TopAnimeQueryParams': { kind: 'INPUT_OBJECT'; name: 'TopAnimeQueryParams'; isOneOf: false; inputFields: [{ name: 'filter'; type: { kind: 'ENUM'; name: 'FilterEnum'; ofType: null; }; defaultValue: null }, { name: 'limit'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'page'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'rating'; type: { kind: 'ENUM'; name: 'RatingEnum'; ofType: null; }; defaultValue: null }, { name: 'sfw'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: 'type'; type: { kind: 'ENUM'; name: 'AnimeTypeEnum'; ofType: null; }; defaultValue: null }]; };
    'Trailer': { kind: 'OBJECT'; name: 'Trailer'; fields: { 'embedUrl': { name: 'embedUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'url': { name: 'url'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'User': { kind: 'OBJECT'; name: 'User'; fields: { 'avatar': { name: 'avatar'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'email': { name: 'email'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'emailVerified': { name: 'emailVerified'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
  };
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}