name: Type check and lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  typecheck-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Type check and lint
        run: pnpm run typecheck && pnpm run lint
        env:
          # use dummy env variables to bypass t3-env check
          DATABASE_URL: libsql://test:xxxx@xxxxxxxxx:3306/test
          DATABASE_AUTH_TOKEN: test
          SENDGRID_API_KEY: test
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          DISCORD_CLIENT_ID: client_id
          DISCORD_CLIENT_SECRET: client_secret
          GOOGLE_CLIENT_ID: client_id
          GOOGLE_CLIENT_SECRET: client_secret
